Dashboard-Boilerplate/app/base/models.py
# -*- encoding: utf-8 -*-
"""
License: MIT
Copyright (c) 2021 - Amberflux
"""

from flask_login import UserMixin
from sqlalchemy import LargeBinary, Column, Integer, String

from app import db, login_manager

from app.base.util import hash_pass

class User(db.Model, UserMixin):

    __tablename__ = 'User'

    id = Column(Integer, primary_key=True)
    username = Column(String, unique=True)
    email = Column(String, unique=True)
    password = Column(LargeBinary)

    def __init__(self, **kwargs):
        for property, value in kwargs.items():
            # depending on whether value is an iterable or not, we must
            # unpack it's value (when **kwargs is request.form, some values
            # will be a 1-element list)
            if hasattr(value, '__iter__') and not isinstance(value, str):
                # the ,= unpack of a singleton fails PEP8 (travis flake8 test)
                value = value[0]

            if property == 'password':
                value = hash_pass( value ) # we need bytes here (not plain str)
                
            setattr(self, property, value)

    def __repr__(self):
        return str(self.username)


@login_manager.user_loader
def user_loader(id):
    return User.query.filter_by(id=id).first()

@login_manager.request_loader
def request_loader(request):
    username = request.form.get('username')
    user = User.query.filter_by(username=username).first()
    return user if user else None

Dashboard-Boilerplate/app/base/forms.py
# -*- encoding: utf-8 -*-
"""
License: MIT
Copyright (c) 2021 - Amberflux
"""

from flask_wtf import FlaskForm
from wtforms import StringField, PasswordField
from wtforms.validators import InputRequired, Email, DataRequired

## login and registration

class LoginForm(FlaskForm):
    username = StringField('Username', id='username_login'   , validators=[DataRequired()])
    password = PasswordField('Password', id='pwd_login'        , validators=[DataRequired()])

class CreateAccountForm(FlaskForm):
    username = StringField('Username'     , id='username_create' , validators=[DataRequired()])
    email    = StringField('Email'        , id='email_create'    , validators=[DataRequired(), Email()])
    password = PasswordField('Password' , id='pwd_create'      , validators=[DataRequired()])

Dashboard-Boilerplate/app/base/__init__.py
# -*- encoding: utf-8 -*-
"""
License: MIT
Copyright (c) 2021 - Amberflux
"""

from flask import Blueprint

blueprint = Blueprint(
    'base_blueprint',
    __name__,
    url_prefix='',
    template_folder='templates',
    static_folder='static'
)

Dashboard-Boilerplate/app/base/routes.py
# -*- encoding: utf-8 -*-
"""
License: MIT
Copyright (c) 2021 - Amberflux
"""

from flask import jsonify, render_template, redirect, request, url_for
from flask_login import (
    current_user,
    login_required,
    login_user,
    logout_user
)

from app import db, login_manager
from app.base import blueprint
from app.base.forms import LoginForm, CreateAccountForm
from app.base.models import User

from app.base.util import verify_pass

@blueprint.route('/')
def route_default():
    return redirect(url_for('base_blueprint.login'))

@blueprint.route('/error-<error>')
def route_errors(error):
    return render_template('errors/{}.html'.format(error))

## Login & Registration

@blueprint.route('/login', methods=['GET', 'POST'])
def login():
    login_form = LoginForm(request.form)
    if 'login' in request.form:
        
        # read form data
        username = request.form['username']
        password = request.form['password']

        # Locate user
        user = User.query.filter_by(username=username).first()
        
        # Check the password
        if user and verify_pass( password, user.password):

            login_user(user)
            return redirect(url_for('base_blueprint.route_default'))

        # Something (user or pass) is not ok
        return render_template( 'login/login.html', msg='Wrong user or password', form=login_form)

    if not current_user.is_authenticated:
        return render_template( 'login/login.html',
                                form=login_form)
    return redirect(url_for('home_blueprint.index'))

@blueprint.route('/create_user', methods=['GET', 'POST'])
def create_user():
    login_form = LoginForm(request.form)
    create_account_form = CreateAccountForm(request.form)
    if 'register' in request.form:

        username  = request.form['username']
        email     = request.form['email'   ]

        user = User.query.filter_by(username=username).first()
        if user:
            return render_template( 'login/register.html', msg='Username already registered', form=create_account_form)

        user = User.query.filter_by(email=email).first()
        if user:
            return render_template( 'login/register.html', msg='Email already registered', form=create_account_form)

        # else we can create the user
        user = User(**request.form)
        db.session.add(user)
        db.session.commit()

        return render_template( 'login/register.html', msg='User created please <a href="/login">login</a>', form=create_account_form)

    else:
        return render_template( 'login/register.html', form=create_account_form)

#adding route for admin
#adding route for app
@blueprint.route('/app')
def appPanel():
    pass

@blueprint.route('/logout')
def logout():
    logout_user()
    return redirect(url_for('base_blueprint.login'))

@blueprint.route('/shutdown')
def shutdown():
    func = request.environ.get('werkzeug.server.shutdown')
    if func is None:
        raise RuntimeError('Not running with the Werkzeug Server')
    func()
    return 'Server shutting down...'

## Errors

@login_manager.unauthorized_handler
def unauthorized_handler():
    return render_template('errors/403.html'), 403

@blueprint.errorhandler(403)
def access_forbidden(error):
    return render_template('errors/403.html'), 403

@blueprint.errorhandler(404)
def not_found_error(error):
    return render_template('errors/404.html'), 404

@blueprint.errorhandler(500)
def internal_error(error):
    return render_template('errors/500.html'), 500

Dashboard-Boilerplate/app/base/templates/base-site-fullscreen.html
<!DOCTYPE html>
<html lang="en">
<head>
  <head>
  
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />

    <title>
      Amberflux DataShield- {% block title %}{% endblock %} | An Amberflux Product
    </title>

    <meta name="description" content="Amberflux DataShield -  Dataset Validation and Correction Tool.">

    <!-- GOOGLE FONTS -->
    <link href="https://fonts.googleapis.com/css?family=Montserrat:400,500|Poppins:400,500,600,700|Roboto:400,500" rel="stylesheet" />
    <link href="https://cdn.materialdesignicons.com/4.4.95/css/materialdesignicons.min.css" rel="stylesheet" />

    <!-- PLUGINS CSS STYLE -->
    <link href="/static/assets/plugins/nprogress/nprogress.css" rel="stylesheet" />

    <!-- SLEEK CSS -->
    <link id="sleek-css" rel="stylesheet" href="/static/assets/css/sleek.css" />

    <!-- FAVICON -->
    <link href="/static/assets/img/favicon.png" rel="shortcut icon" />

    <!--
      HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries
    -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
    <script src="/static/assets/plugins/nprogress/nprogress.js"></script>

    <!-- Specific Page CSS goes HERE  -->  
    {% block stylesheets %}{% endblock stylesheets %}

</head>

</head>
<body class="" id="body">
  <div class="container d-flex flex-column justify-content-between vh-100">

    {% block content %}{% endblock content %}

    {% include 'site_template/footer-fullscreen.html' %}

  </div>
</body>

  <!-- Specific Page JS goes HERE  -->
  {% block javascripts %}{% endblock javascripts %}

</html>

Dashboard-Boilerplate/app/base/templates/base-site.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
<head>
  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <meta name="viewport" content="width=device-width, initial-scale=1" />

  <title>
    Amberflux DataShield- {% block title %}{% endblock %} | An Amberflux Product
  </title>

  <meta name="description" content="Amberflux DataShield - Dataset Validation and Correction Tool.">

  <!-- GOOGLE FONTS -->
  <link href="https://fonts.googleapis.com/css?family=Montserrat:400,500|Poppins:400,500,600,700|Roboto:400,500" rel="stylesheet" />
  <link href="https://cdn.materialdesignicons.com/4.4.95/css/materialdesignicons.min.css" rel="stylesheet" />

  <!-- PLUGINS CSS STYLE -->
  <link href="/static/assets/plugins/nprogress/nprogress.css" rel="stylesheet" />

  <!-- No Extra plugin used -->

  <link href="/static/assets/plugins/jvectormap/jquery-jvectormap-2.0.3.css" rel="stylesheet" />

  <link href="/static/assets/plugins/daterangepicker/daterangepicker.css" rel="stylesheet" />
  <link href="/static/assets/plugins/toastr/toastr.min.css" rel="stylesheet" />

  <!-- SLEEK CSS -->
  <link id="sleek-css" rel="stylesheet" href="/static/assets/css/sleek.css" />

  <!-- FAVICON -->
  <link href="/static/assets/img/favicon.png" rel="shortcut icon" />

  <!--
    HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries
  -->
  <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
  <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
    <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
  <![endif]-->
  <script src="/static/assets/plugins/nprogress/nprogress.js"></script>

  <!-- Specific Page CSS goes HERE  -->
  {% block stylesheets %}{% endblock stylesheets %}

</head>
<body class="header-fixed sidebar-fixed sidebar-dark header-light" id="body">
  
  <script>
    NProgress.configure({ showSpinner: false });
    NProgress.start();
  </script>
  
  <div id="toaster"></div>

  <div class="wrapper">
    
    {% include 'site_template/sidebar.html' %}

    <div class="page-wrapper">

      {% include 'site_template/navigation.html' %}

      <div class="content-wrapper">

        <div class="content">						 

            {% block content %}{% endblock content %}
            
        </div>

        {% include 'site_template/sidebar-right.html' %}        

      </div>

      {% include 'site_template/footer.html' %}

    </div>
  </div>

{% include 'site_template/scripts.html' %}

<!-- Specific Page JS goes HERE  -->
{% block javascripts %}{% endblock javascripts %}

<script src="/static/assets/js/sleek.bundle.js"></script>

</body>

</html>

Dashboard-Boilerplate/app/base/templates/login/login.html
{% extends "base-site-fullscreen.html" %}

{% block title %} Login {% endblock %}

{% block content %}
    <div class="row justify-content-center mt-5">
      <div class="col-xl-5 col-lg-6 col-md-10">
        <div class="card">
          <div class="card-header bg-primary">
            <div class="app-brand">
              <a href="https://amberflux.com/">
                <svg class="brand-icon" xmlns="http://www.w3.org/2000/svg" preserveAspectRatio="xMidYMid" width="30" height="33"
                  viewBox="0 0 30 33">
                  <g fill="none" fill-rule="evenodd">
                    <path class="logo-fill-blue" fill="#7DBCFF" d="M0 4v25l8 4V0zM22 4v25l8 4V0z" />
                    <path class="logo-fill-white" fill="#FFF" d="M11 4v25l8 4V0z" />
                  </g>
                </svg>
                <span class="brand-name">Amberflux DataShield</span>
              </a>
            </div>
          </div>
          <div class="card-body p-5">

            <h4 class="text-dark mb-5">
              
              {% if msg %}
                {{ msg | safe }}
              {% else %}
              <span>
                Use default credentials: test / pass
              </span>              
              {% endif %}               
            </h4>
            
            <form role="form" method="post" action="">

              {{ form.hidden_tag() }} 
  
              <div class="row">
                <div class="form-group col-md-12 mb-4">
                  {{ form.username(placeholder="Username", class="form-control input-lg") }}
                </div>
                <div class="form-group col-md-12 ">
                  {{ form.password(placeholder="Password", class="form-control input-lg", type="password") }}
                </div>
                <div class="col-md-12">
                  <div class="d-flex my-2 justify-content-between">
                    <div class="d-inline-block mr-3">
                      <label class="control control-checkbox">Remember me
                        <input type="checkbox" />
                        <div class="control-indicator"></div>
                      </label>

                    </div>
                    <p><a class="text-blue" href="#">Forgot Your Password?</a></p>
                  </div>

                  <button type="submit" name="login" class="btn btn-lg btn-primary btn-block mb-4">Login</button>

                  <p>Don't have an account yet ?
                    <a class="text-blue" href={{ url_for('base_blueprint.create_user') }} >Register</a>
                  </p>

                </div>
              </div>
            </form>
          </div>
        </div>
      </div>
    </div>
{% endblock content %}

<!-- Specific Page JS goes HERE  -->
{% block javascripts %}{% endblock javascripts %}

Dashboard-Boilerplate/app/base/templates/login/register.html
{% extends "base-site-fullscreen.html" %}

{% block title %} Login {% endblock %}

{% block content %}

  <div class="row justify-content-center mt-5">
    <div class="col-xl-5 col-lg-6 col-md-10">
      <div class="card">
        <div class="card-header bg-primary">
          <div class="app-brand">
            <a href="https://amberflux.com/">
              <svg class="brand-icon" xmlns="http://www.w3.org/2000/svg" preserveAspectRatio="xMidYMid" width="30"
                height="33" viewBox="0 0 30 33">
                <g fill="none" fill-rule="evenodd">
                  <path class="logo-fill-blue" fill="#7DBCFF" d="M0 4v25l8 4V0zM22 4v25l8 4V0z" />
                  <path class="logo-fill-white" fill="#FFF" d="M11 4v25l8 4V0z" />
                </g>
              </svg>
              <span class="brand-name">Amberflux DataShield</span>
            </a>
          </div>
        </div>
        <div class="card-body p-5">

            <h4 class="text-dark mb-5">
              {% if msg %}
                {{ msg | safe }}
              {% else %}
                  Add your credentials OR  
                  <br />
                  <a href={{ url_for('base_blueprint.login') }}>authenticate</a> using an existing account.
              {% endif %}               
            </h4>
              
            <form role="form" method="post" action="">

              {{ form.hidden_tag() }}                     
            
            <div class="row">
              
              <div class="form-group col-md-12 mb-4">
                {{ form.username(placeholder="Username", class="form-control input-lg") }}
              </div>

              <div class="form-group col-md-12 mb-4">
                {{ form.email(placeholder="Email", class="form-control input-lg") }}
              </div>

              <div class="form-group col-md-12 ">
                  {{ form.password(placeholder="Password", class="form-control input-lg", type="password") }}
              </div>

              <div class="col-md-12">
                <div class="d-inline-block mr-3">
                  <label class="control control-checkbox">
                    <input type="checkbox" />
                    <div class="control-indicator"></div>
                    I Agree the terms and conditions
                  </label>

                </div>

                <button type="submit" name="register" class="btn btn-lg btn-primary btn-block mb-4">Sign Up</button>
                
                <p>Already have an account?
                  <a class="text-blue" href={{ url_for('base_blueprint.login') }} >Login</a>
                </p>

              </div>
            </div>
          </form>

        </div>
      </div>
    </div>
  </div>

{% endblock content %}

<!-- Specific Page JS goes HERE  -->
{% block javascripts %}{% endblock javascripts %}

Dashboard-Boilerplate/app/base/templates/site_template/footer-fullscreen.html
    <div class="copyright pl-0">
        <p class="text-center">&copy; <a class="text-primary" href="http://www.amberflux.com/">Amberflux</a> - 
            <a href="https://amberflux.com/"> DataShield </a> 
        </p>
    </div>

Dashboard-Boilerplate/app/base/templates/site_template/footer.html
<footer class="footer mt-auto">
    <div class="copyright bg-white">
        <p>&copy; <a class="text-primary" href="http://www.amberflux.com/">Amberflux</a> - 
            <a href="#"> DataShield </a> 
        </p>
    </div>
</footer>

Dashboard-Boilerplate/app/base/templates/site_template/navigation.html
          <header class="main-header " id="header">
            <nav class="navbar navbar-static-top navbar-expand-lg">
              <!-- Sidebar toggle button -->
              <button id="sidebar-toggler" class="sidebar-toggle">
                <span class="sr-only">Toggle navigation</span>
              </button>
              <!-- search form -->
              <div class="search-form d-none d-lg-inline-block">
                <div class="input-group">
                  <button type="button" name="search" id="search-btn" class="btn btn-flat">
                    <i class="mdi mdi-magnify"></i>
                  </button>
                  <input type="text" name="query" id="search-input" class="form-control" placeholder="'button', 'chart' etc."
                    autofocus autocomplete="off" />
                </div>
                <div id="search-results-container">
                  <ul id="search-results"></ul>
                </div>
              </div>

              <div class="navbar-right ">
                <ul class="nav navbar-nav">
                  
                  <li class="right-sidebar-in right-sidebar-2-menu">
                    <i class="mdi mdi-settings"></i>
                  </li>
                  <!-- User Account -->
                  <li class="dropdown user-menu">
                    <button href="#" class="dropdown-toggle nav-link" data-toggle="dropdown">
                      <img src="https://avatars.dicebear.com/api/initials/{{ current_user.username }}.svg" class="user-image" alt="image" onerror="this.onerror=null; this.src='/static/assets/img/user/user1.png';" />
                      <span class="d-none d-lg-inline-block">
                        {{ current_user.username }}
                      </span>
                    </button>
                    <ul class="dropdown-menu dropdown-menu-right">
                      <!-- User image -->
                      <li class="dropdown-header">
                        <img src="https://avatars.dicebear.com/api/initials/{{ current_user.username }}.svg" class="img-circle" alt="image" onerror="this.onerror=null; this.src='/static/assets/img/user/user1.png';" />
                        <div class="d-inline-block">
                          {{ current_user.username }} <small class="pt-1">{{ current_user.email }}</small>
                        </div>
                      </li>

                      <li>
                        <a href="user-profile.html">
                          <i class="mdi mdi-account"></i> My Profile
                        </a>
                      </li>
                      <li class="right-sidebar-in">
                        <a href="javascript:0"> <i class="mdi mdi-settings"></i> Setting </a>
                      </li>

                      <li class="dropdown-footer">
                        <a href={{ url_for('base_blueprint.logout') }} > <i class="mdi mdi-logout"></i> Log Out </a>
                      </li>
                    </ul>
                  </li>
                </ul>
              </div>
            </nav>


          </header>

Dashboard-Boilerplate/app/base/templates/site_template/scripts.html
<script src="/static/assets/plugins/jquery/jquery.min.js"></script>
<script src="/static/assets/plugins/slimscrollbar/jquery.slimscroll.min.js"></script>
<script src="/static/assets/plugins/jekyll-search.min.js"></script>
<script src="/static/assets/plugins/toastr/toastr.min.js"></script>

Dashboard-Boilerplate/app/base/templates/site_template/sidebar-right.html
        <div class="right-sidebar-2">
          <div class="right-sidebar-container-2">
            <div class="slim-scroll-right-sidebar-2">

            <div class="right-sidebar-2-header">
              <h2>Layout Settings</h2>
              <p>User Interface Settings</p>
              <div class="btn-close-right-sidebar-2">
                <i class="mdi mdi-window-close"></i>
              </div>
            </div>

            <div class="right-sidebar-2-body">
              <span class="right-sidebar-2-subtitle">Header Layout</span>
              <div class="no-col-space">
                <a href="javascript:void(0);" class="btn-right-sidebar-2 header-fixed-to btn-right-sidebar-2-active">Fixed</a>
                <a href="javascript:void(0);" class="btn-right-sidebar-2 header-static-to">Static</a>
              </div>

              <span class="right-sidebar-2-subtitle">Sidebar Layout</span>
              <div class="no-col-space">
                <select class="right-sidebar-2-select" id="sidebar-option-select">
                  <option value="sidebar-fixed">Fixed Default</option>
                  <option value="sidebar-fixed-minified">Fixed Minified</option>
                  <option value="sidebar-fixed-offcanvas">Fixed Offcanvas</option>
                </select>
              </div>

              <span class="right-sidebar-2-subtitle">Header Background</span>
              <div class="no-col-space">
                <a href="javascript:void(0);" class="btn-right-sidebar-2 btn-right-sidebar-2-active header-light-to">Light</a>
                <a href="javascript:void(0);" class="btn-right-sidebar-2 header-dark-to">Dark</a>
              </div>

              <span class="right-sidebar-2-subtitle">Navigation Background</span>
              <div class="no-col-space">
                <a href="javascript:void(0);" class="btn-right-sidebar-2 btn-right-sidebar-2-active sidebar-dark-to">Dark</a>
                <a href="javascript:void(0);" class="btn-right-sidebar-2 sidebar-light-to">Light</a>
              </div>

              <div class="d-flex justify-content-center" style="padding-top: 30px">
                <div id="reset-options" style="width: auto; cursor: pointer" class="btn-right-sidebar-2 btn-reset">Reset
                  Settings</div>
              </div>

            </div>

          </div>
        </div>
        

Dashboard-Boilerplate/app/base/templates/site_template/sidebar.html
    <aside class="left-sidebar bg-sidebar">
    
      <div id="sidebar" class="sidebar">
      
        <!-- Aplication Brand -->
        <div class="app-brand">
          <a href="/">
              <svg
                class="brand-icon"
                xmlns="http://www.w3.org/2000/svg"
                preserveAspectRatio="xMidYMid"
                width="30"
                height="33"
                viewBox="0 0 30 33"
              >
                <g fill="none" fill-rule="evenodd">
                  <path
                    class="logo-fill-blue"
                    fill="#7DBCFF"
                    d="M0 4v25l8 4V0zM22 4v25l8 4V0z"
                  />
                  <path class="logo-fill-white" fill="#FFF" d="M11 4v25l8 4V0z" />
                </g>
              </svg>
              <span class="brand-name">Amberflux DataShield</span>
          </a>
        </div>

        <!-- begin sidebar scrollbar -->
        <div class="sidebar-scrollbar">

          <!-- sidebar menu -->
          <ul class="nav sidebar-inner" id="sidebar-menu">
                
            <li class="has-sub active expand" >
              <a class="sidenav-item-link" href="javascript:void(0)" data-toggle="collapse" data-target="#dashboard"
                aria-expanded="false" aria-controls="dashboard">
                <i class="mdi mdi-view-dashboard-outline"></i>
                <span class="nav-text">Dashboard</span> <b class="caret"></b>
              </a>
              <ul  class="collapse show"  id="dashboard"
                data-parent="#sidebar-menu">
                <div class="sub-menu">
                  
                      <li  class="active" >
                        <a class="sidenav-item-link" href="/">
                          <span class="nav-text">Dashboard</span>
                          
                        </a>
                      </li>
                    
                      <li >
                        <a class="sidenav-item-link" href="/analytics">
                          <span class="nav-text">Analytics</span>
                          
                          <span class="badge badge-success">new</span>
                          
                        </a>
                      </li>

                </div>
              </ul>
            </li>
                
            <li class="has-sub" >
              <a class="sidenav-item-link" href="javascript:void(0)" data-toggle="collapse" data-target="#app"
                aria-expanded="false" aria-controls="app">
                <i class="mdi mdi-pencil-box-multiple"></i>
                <span class="nav-text">App</span> <b class="caret"></b>
              </a>
              <ul  class="collapse"  id="app"
                data-parent="#sidebar-menu">
                <div class="sub-menu">
                    
                      <li >
                        <a class="sidenav-item-link" href="/interface">
                          <span class="nav-text">Correction Interface</span>
                          
                        </a>
                      </li>

                      <li >
                        <a class="sidenav-item-link" href="/admin">
                          <span class="nav-text">Admin Form Builder</span>
                          
                        </a>
                      </li>

                      <li >
                        <a class="sidenav-item-link" href="/page-contacts">
                          <span class="nav-text">Contacts</span>
                          
                        </a>
                      </li>

                </div>
              </ul>
            </li>
            
            <li >
              <a href={{ url_for('base_blueprint.logout') }} > 
                <i class="mdi mdi-settings"></i>
                <span class="nav-text">Settings</span> 
              </a>
            </li>
                 
            <li >
              <a href={{ url_for('base_blueprint.logout') }} > 
                <i class="mdi mdi-logout"></i>
                <span class="nav-text">Logout</span> 
              </a>
            </li>
                
          </ul>

        </div>

      </div>

    </aside>